import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import { cn } from "@/lib/utils";
import "./globals.css";
import Image from "next/image";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import { ThemeProvider } from "next-themes";
import SidebarComponent from "./components/Sidebar";

export const metadata: Metadata = {
  title: "Doses of Imaan",
  description: "Generated by create next app",
  keywords: "dosesofislam,dosesofimaan,Islam,Imaan,Ihsaan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(GeistSans.variable, GeistMono.variable)}
      suppressHydrationWarning
    >
      <head>
        <link rel="icon" type="image/x-icon" href="favicon.ico" />
      </head>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className="flex flex-col min-h-screen bg-background font-sans antialiased">
          <SidebarProvider defaultOpen={true}>
            <SidebarComponent />
            {/* <SidebarTrigger className="ml-2 aspect-square hidden md:block" /> */}
            <main className="container flex flex-col">
              <div className="border-b flex justify-between md:hidden py-2 px-3 sticky top-0 z-[20] bg-white dark:bg-gray-700">
                <SidebarTrigger className="ml-2 aspect-square" />
                <Image
                  src="/logo.png"
                  alt="Brand logo"
                  width={32}
                  height={32}
                  className="object-contain"
                />
                <div className="w-[28px]"></div>
              </div>

              <div className="z-10">{children}</div>
            </main>
          </SidebarProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
